       
# cada fase tem suas palavras e velocidade que pode ser ajustado com os valores 
#"min_speed": 1, "max_speed": 1 de cada string o min e a velocidade minima da palavra o max e a maxima que ela ira aparecer



fases = {
    1: {"palavras": ["fel", "vil", "mal", "ver", "mãe", "sob", "ter", "ego", "bem", "mas", "dom", "bom", "vir", "são", "dar", 
        "ora", "vão", "que", "era", "seu", "nós", "elo", "com", "luz", "mim", "foi", "réu", "tal", "rol", "uma", "fim", "até", "por", "lua", 
        "hum", "dor", "vez", "pós", "vis", "ler", "sol", "ato", "pai", "sem", "dia", "irá", "dou", "pro", "eis", "rua", "ode", "tez", "nem", 
        "voz", "tão", "ajo", "fiz", "meu", "lei", "voo", "mau", "afã", "pôr", "mão", "num", "olá", "dês", "lar", "sua", "for", "rio", 
        "cia", "daí", "jus", "fez", "ira", "amo", "som", "via", "sim", "nau", "uso", "más", "rei", "jaz", "tem", "mês", "boa", "asa", "aia", 
        "uns", "ido", "pal", "ele", "clã"], "min_speed": 1, "max_speed": 1},

    2: {"palavras": ["amor", "fato", "viés", "você", "mito", "como", "caos", "esmo", "brio", "ação", "vide", "sede", "pois", "após", "vida", "casa", "medo", "saga", 
        "auge", "ônus", "vovó", "sina", "ermo", "além", "mais", "pela", "suma", "mote", "tolo", "urge", "idem", "zelo", "crer", "tudo", "veio", "apto", 
        "pude", "amar", "ruim", "área", "para", "rude", "será", "doce", "coxo", "ater", "soar", "cota", "trás", "fase", "ente", "logo", "auto", "alma", 
        "deus", "voga", "onde", "arte", "pelo", "sido", "jugo", "ante", "cedo", "rima", "meio", "traz", "numa", "isso", "meta", "sela", "cujo", "noia", 
        "sair", "cela", "teor", "asco", "face", "foco", "alvo", "ódio", "nojo", "alto", "agir", "base", "pose", "vale", "teve", "todo", "ócio", "eita", 
        "rito", "irão", "novo", "ágil", "bojo", "tese", "alva", "nada", "quer", "alta"], "min_speed": 1, "max_speed": 2},

    3: {"palavras":["sagaz", "âmago", "termo", "negro", "êxito", "mexer", "nobre", "senso", "afeto", "ética", "algoz", "plena", "fazer", "assim", "tênue", "mútua", "sobre", "aquém", "vigor", "seção", "poder", 
        "sutil", "porém", "fosse", "cerne", "ideia", "sanar", "audaz", "moral", "inato", "quiçá", "desde", "muito", "justo", "sonho", "honra", "torpe", "razão", "amigo", "ícone", "etnia", "égide",
        "fútil", "anexo", "dengo", "tange", "haver", "lapso", "então", "expor", "tempo", "boçal", "seara", "hábil", "mútuo", "saber", "casal", "graça", "ávido", "óbice", "xibiu", "dizer", "ardil", 
        "pesar", "estar", "dever", "causa", "sendo", "tenaz", "ainda", "pária", "brado", "coser", "crivo", "temor", "genro", "posse", "comum", "ápice", "prole", "ânimo", "assaz", "ceder", "corja", 
        "pauta", "detém", "fugaz", "censo", "ânsia", "culto", "digno", "atroz", "mundo", "forte", "vulgo", "mesmo", "vício", "gleba", "saúde", "criar"], "min_speed": 1, "max_speed": 2},

    4: {"palavras":["exceto", "cínico", "idôneo", "âmbito", "néscio", "mister", "índole", "vereda", "defina", "apogeu", "inócuo", "convém", "utopia", "escopo", "sádico", "ênfase", "idiota", "alusão", "mérito", 
        "casual", "hostil", "cético", "anseio", "legado", "gentil", "pressa", "hétero", "alheio", "paixão", "nocivo", "clichê", "infame", "exímio", "afável", "dádiva", "também", "adorno", "êxtase", 
        "larica", "otário", "sóbrio", "astuto", "aferir", "adesão", "glória", "sessão", "solene", "limiar", "julgar", "embora", "ensejo", "apreço", "hábito", "lábaro", "nuance", "formal", "ímpeto", 
        "eficaz", "outrem", "perene", "dispor", "júbilo", "ocioso", "alento", "difuso", "ilação", "escusa", "cessão", "exílio", "facção", "lúdico", "objeto", "acesso", "abster", "alçada", "desejo", 
        "mulher", "axioma", "acento", "buscar", "etéreo", "tácito", "quando", "sanção", "mazela", "cobiça", "penhor", "cortês", "isento", "sisudo", "eximir", "avidez", "prazer", "sempre", "vulgar", 
        "receio", "remoto", "fático", "nômade", "rotina"], "min_speed": 1, "max_speed": 2},

    5: {"palavras":["empatia", "aurélio", "cônjuge", "embuste", "exceção", "verbete", "caráter", "efêmero", "prolixo", "idílico", "família", "análogo", "genuíno", "sublime", "estória", "inferir", "pêsames", 
        "apático", "sucinto", "acepção", "redimir", "cultura", "pródigo", "astúcia", "estigma", "audácia", "recesso", "virtude", "icônico", "soberba", "mitigar", "refutar", "exortar", "cinismo", 
        "mórbido", "trivial", "estável", "aspecto", "sucesso", "síntese", "alegria", "luxúria", "cordial", "anátema", "imputar", "ademais", "emergir", "orgulho", "escória", "excerto", "candura", 
        "deboche", "através", "litígio", "almejar", "saudade", "coragem", "contudo", "amizade", "frívolo", "salutar", "escroto", "racismo", "oriundo", "ambíguo", "austero", "alcunha", "quimera", 
        "relação", "ambição", "imersão", "excesso", "erudito", "sensato", "ciência", "demanda", "modesto", "fomento", "piedade", "conciso", "colosso", "parcial", "exótico", "volátil", "notório",
        "vigente", "híbrido", "bizarro", "padecer", "auferir", "hesitar", "profano", "leviano", "inércia", "ansioso", "sentido", "sórdido", "déspota", "ignóbil", "intenso"], "min_speed": 2, "max_speed": 4},

    6: {"palavras":["inerente", "respeito", "peculiar", "denegrir", "genocida", "anuência", "equidade", "deferido", "prudente", "essência", "iminente", "pandemia", "desgraça", "misógino", "eminente", "premissa", 
        "invasivo", "abstrato", "alienado", "extensão", "empírico", "rapariga", "conceito", "ardiloso", "talarico", "ascensão", "reiterar", "devaneio", "lascívia", "prodígio", "relativo", "inefável", 
        "passível", "conserto", "gratidão", "destarte", "analogia", "inserção", "remissão", "modéstia", "fomentar", "apologia", "despeito", "ativista", "inóspito", "medíocre", "retórica", "monótono", 
        "história", "alicerce", "concerne", "respaldo", "proceder", "sinônimo", "perfídia", "portanto", "primazia", "complexo", "metódico", "espectro", "rechaçar", "paradoxo", "critério", "demagogo", 
        "amálgama", "consiste", "suscitar", "comunhão", "sucumbir", "distinto", "singular", "abnegado", "escárnio", "notívago", "desfecho", "contexto", "objetivo", "processo", "refletir", "vocábulo", 
        "problema", "elegível", "obstante", "impávido", "incrível", "redenção", "epifania", "maestria", "desígnio", "solícito", "mediante", "endêmico", "reflexão", "preceito", "jurídico", "instigar", 
        "imanente", "insípido", "paralelo", "genérico"], "min_speed": 2, "max_speed": 4},

    7: {"palavras":["perspicaz", "recíproco", "concessão", "impressão", "escrúpulo", "supérfluo", "retificar", "paradigma", "propósito", "dicotomia", "presunção", "concepção", "ratificar", "hipócrita", "plenitude", 
        "implícito", "essencial", "corolário", "hegemonia", "incidente", "esdrúxulo", "altruísmo", "altruísta", "vagabundo", "hermético", "esperança", "confiança", "aleatório", "promíscuo", "persuadir", 
        "deliberar", "sapiência", "indelével", "diligente", "demasiado", "mesquinho", "descrição", "impetuoso", "inusitado", "regozijar", "resignado", "compaixão", "prudência", "eminência", "discrição", 
        "pretensão", "percepção", "ordinário", "explícito", "analítico", "exequível", "autonomia", "subjetivo", "nostalgia", "companhia", "resolução", "outrossim", "autóctone", "paciência", "fidedigno", 
        "dissensão", "supressão", "expressão", "desdenhar", "taciturno", "constante", "imparcial", "ignorante", "consoante", "autêntico", "arrogante", "desumilde", "execrável", "obstinado", "discorrer", 
        "jactância", "arcabouço", "eloquente", "restrição", "submissão", "interesse", "cognitivo", "adjacente", "instância", "limítrofe", "iminência", "sintético", "relevante", "presságio", "humildade", 
        "liberdade", "empecilho", "excelente", "irascível", "ludibriar", "insensato", "plausível", "convicção", "primícias", "incógnita"], "min_speed": 2, "max_speed": 4},

    8: {"palavras":["dicionário", "intrínseco", "prescindir", "presunçoso", "diligência", "corroborar", "intempérie", "detrimento", "parcimônia", "maturidade", "inspiração", "referência", "inexorável", "pragmático", 
        "prepotente", "incipiente", "disruptivo", "serenidade", "sororidade", "iniquidade", "auspicioso", "pertinente", "arbitrário", "indulgente", "hipocrisia", "sagacidade", "resignação", "preconizar", 
        "vislumbrar", "precedente", "incidência", "lisonjeado", "suscetível", "entretanto", "disposição", "excêntrico", "fleumático", "tribulação", "preliminar", "subestimar", "depreender", "anacrônico", 
        "escrutínio", "excelência", "equivocado", "ingerência", "indolência", "democracia", "retrógrado", "infortúnio", "compassivo", "importante", "contemplar", "pejorativo", "restringir", "proposição", 
        "sintetizar", "subjacente", "intrínseca", "primordial", "signatário", "conjuntura", "alteridade", "itinerário", "dissolução", "coercitivo", "no entanto", "finalidade", "esplêndido", "constância", 
        "necessário", "designação", "pecuniária", "espontâneo", "transeunte", "pusilânime", "disciplina", "felicidade", "sarcástico", "privilégio", "verossímil", "exacerbado", "pernóstico", "relevância", 
        "idoneidade", "desprovido", "inferência", "reverberar", "satisfação", "divergente", "pernicioso", "disseminar", "esporádico", "meticuloso", "influência", "retumbante", "fornicação", "resiliente", 
        "consolidar", "etimologia"], "min_speed": 2, "max_speed": 4},

    9: {"palavras":["significado", "perspectiva", "resiliência", "dissimulado", "vicissitude", "complacente", "contundente", "peremptório", "compreensão", "comorbidade", "perspicácia", "expectativa", "pressuposto", 
        "subterfúgio", "beneplácito", "experiência", "preconceito", "consonância", "indiferente", "pretensioso", "transcender", "necessidade", "intensidade", "imensurável", "contingente", "proeminente", 
        "beligerante", "superficial", "concernente", "benignidade", "animosidade", "contencioso", "intervenção", "inenarrável", "incumbência", "vocabulário", "cumprimento", "resistência", "antagonismo", 
        "compreender", "indiferença", "reivindicar", "subsequente", "supracitado", "integridade", "diversidade", "estereótipo", "indulgência", "ambiguidade", "deliberação", "especulação", "elucubração", 
        "divergência", "austeridade", "proveniente", "importância", "indubitável", "prognóstico", "tergiversar", "negligência", "estabelecer", "heterogêneo", "identificar", "displicente", "consciência", 
        "oportunista", "benevolente", "conveniente", "excepcional", "discriminar", "redundância", "congruência", "pragmatismo", "providência", "admoestação", "substantivo", "conferência", "comprimento", 
        "sistemático", "facultativo", "compulsório", "intersecção", "verborragia", "desenvolver", "melancólico", "dificuldade", "relativizar", "subordinado", "intelectual", "honestidade", "contradição", 
        "substancial", "generalizar", "competência", "retificação", "emblemático", "amabilidade", "procedência", "conservador", "autoritário"], "min_speed": 2, "max_speed": 4},

    10: {"palavras":["perseverança", "remanescente", "condolências", "prerrogativa", "extrovertido", "complacência", "procrastinar", "discrepância", "determinação", "independente", "consequência", "intermitente", 
         "conveniência", "compartilhar", "benevolência", "contingência", "eclesiástico", "transgressão", "consideração", "felicitações", "não obstante", "concomitante", "convergência", "conhecimento", 
         "cordialidade", "cumplicidade", "convencional", "subsistência", "proselitismo", "disseminação", "coincidência", "sistematizar", "complexidade", "prescindível", "controvérsia", "ninfomaníaco", 
         "imprevisível", "escatológico", "impertinente", "inverossímil", "libertinagem", "interlocutor", "conformidade", "displicência", "proporcionar", "intempestivo", "maledicência", "extemporâneo", 
         "fraternidade", "intolerância", "resplandecer", "perseverante", "misericórdia", "estabilidade", "persistência", "mediocridade", "maquiavélico", "hermenêutica", "aquiescência", "circunspecto", 
         "coexistência", "preeminência", "proeminência", "oportunidade", "protagonista", "complementar", "introvertido", "constituição", "parcialmente", "consolidação", "escarnecedor", "deslumbrante", 
         "entendimento", "destinatário", "consistência", "parcialidade", "interessante", "estigmatizar", "procedimento", "caracterizar", "generosidade", "incircunciso", "circuncidado", "condicionado", 
         "enclausurado", "prosperidade", "literalmente", "superestimar", "desenvoltura", "fragmentação", "proficiência", "profissional", "simplicidade", "depreciativo", "incolumidade", "legitimidade", 
         "inescrutável", "beneficência", "sobremaneira", "predestinado"], "min_speed": 2, "max_speed": 4},

    11: {"palavras":["reciprocidade", "contemporâneo", "inconveniente", "heterossexual", "circunstância", "discernimento", "solidariedade", "promiscuidade", "ressignificar", "intransigente", "credibilidade", 
         "discriminação", "epistemologia", "transcendente", "aprovisionado", "contrapartida", "assintomático", "incongruência", "comprobatório", "reminiscência", "perpendicular", "ressentimento", 
         "possibilidade", "estereotipado", "recenseamento", "veementemente", "intermediário", "preponderante", "indispensável", "hodiernamente", "subjetividade", "singularidade", "subserviência", 
         "longanimidade", "transformação", "autenticidade", "convalescença", "pormenorizado", "instabilidade", "independência", "incontinência", "introspectivo", "superveniente", "sensibilidade", 
         "eventualmente", "multifacetado", "reivindicação", "elegibilidade", "indissociável", "superestimado", "contraditório", "a despeito de", "latifundiário", "recalcitrante", "quintessência", 
         "desmistificar", "filho pródigo", "incredulidade", "inconsequente", "sobressalente", "ininteligível", "inescrupuloso", "comportamento", "personalidade", "implementação", "monossilábico", 
         "indescritível", "integralmente", "magnificência", "provavelmente", "homogeneidade", "incondicional", "precipuamente", "peculiaridade", "circunscrição", "serendipidade", "consentimento", 
         "contentamento", "convalescente", "remanejamento", "consciencioso", "incandescente", "correlacionar", "predisposição", "versatilidade", "conscientizar", "arrefecimento", "desnecessário", 
         "irresponsável", "supersticioso", "identificação", "representação", "indeterminado", "imperceptível", "incognoscível", "reconciliação", "especificação", "monocromático", "receptividade", 
         "ressarcimento"], "min_speed": 2, "max_speed": 4},

    12: {"palavras":["imprescindível", "condescendente", "idiossincrasia", "concupiscência", "característica", "extraordinário", "demasiadamente", "intercorrência", "irrepreensível", "pronta-entrega", 
         "consubstanciar", "incomensurável", "discricionário", "preponderância", "arbitrariedade", "especificidade", "posteriormente", "imprescritível", "intransponível", "contextualizar", 
         "empreendimento", "entretenimento", "ancestralidade", "transcendental", "arrependimento", "paulatinamente", "relacionamento", "infraestrutura", "imparcialidade", "bem-aventurado", 
         "revolucionário", "superveniência", "atenciosamente", "reconhecimento", "ponto de vista", "transcendência", "periodicamente", "democratização", "insignificante", "diligentemente", 
         "inconsistência", "despretensioso", "personificação", "impessoalidade", "socioambiental", "espontaneidade", "funcionalidade", "trazer à baila", "procrastinação", "cônjuge virago", 
         "estelionatário", "intransigência", "desprendimento", "principalmente", "aplicabilidade", "potencialidade", "estratificação", "extraordinária", "licenciosidade", "procrastinador",
         "prestatividade", "excentricidade", "epistemológico", "dissolutamente", "pusilanimidade", "inconveniência", "congratulações", "exequibilidade", "biodiversidade", "insubstituível", 
         "individualismo", "papibaquígrafo", "jurisprudência", "resplandecente", "disponibilizar", "abundantemente", "coercitividade", "acessibilidade", "plausibilidade", "exclusivamente", 
         "internalização", "constantemente", "perfeccionista", "credenciamento", "menção honrosa", "impressionante", "multiplicidade", "aleatoriamente", "questionamento", "esclarecimento",
         "grandiloquente", "implicitamente", "permissividade", "minuciosamente", "frequentemente", "indiscriminado", "concessionária", "transfiguração", "sobrecarregado", "intermunicipal"], "min_speed": 3, "max_speed": 4},

    13: {"palavras":["condescendente", "cônjuge", "caráter", "cínico", "concessão", "corroborar", "condolências", "contemporâneo", "concepção", "complacente", "corolário", "complacência", "contundente", 
         "concupiscência", "conceito", "característica", "condescendência", "convém", "compreensão", "comorbidade", "cultura", "como", "confiança", "conserto", "circunstância", "caos", "consequência", 
         "casual", "cinismo", "cético", "concerne", "céu", "compaixão", "consonância", "conveniência", "compartilhar", "complexo", "cordial", "contingência", "critério", "clichê", "consiste", "contingente", 
         "comunhão", "contexto", "concernente", "companhia", "candura", "cerne", "contencioso", "compassivo", "constante", "contemplar", "consideração", "coragem", "contudo", "consoante", "cumprimento", 
         "concomitante", "carência", "compreender", "conjuntura", "cognitivo", "convergência", "conhecimento", "ciência", "cordialidade", "coercitivo", "cumplicidade", "constância", "conciso", "colosso", 
         "concerto", "convencional", "cessão", "condição", "convicção", "contenda", "conceder", "casa", "canalha", "credibilidade", "coerente", "coincidência", "concomitantemente", "colapso", "caridade", 
         "custódia", "conhecer", "conforme", "complexidade", "cuidado", "controvérsia", "consciência", "coerência", "contíguo", "conveniente", "cobiça", "casal", "cortês"], "min_speed": 3, "max_speed": 4}
}
